version: '2'
services:
  myapp:
    image: 'docker.io/bitnami/codeigniter:3-debian-10'
    ports:
      - '80:8000'
    volumes:
      - './:/app'
    depends_on:
      - mariadb
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATBASE=ventas
